#
# Copyright 2015 Host Mobility AB
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= mx4_v61.o ../mx4_common/cmd_mx4_pic.o ../mx4_common/cmd_mx4_product.o
obj-y 	+= ../mx4_common/mx4_common.o
obj-$(CONFIG_FSL_DCU_FB) += dcu.o
