# Copyright (c) 2011-2016 Host Mobility AB
# SPDX-License-Identifier:      GPL-2.0+

include $(srctree)/board/nvidia/common/common.mk

obj-y	+= mx4_mil.o ../mx4_common/cmd_mx4_pic.o ../mx4_common/cmd_mx4_product.o
obj-y 	+= ../mx4_common/mx4_common.o
